theme: jekyll-theme-minimal
title: Wii Shop Channel - In-place Service Replacement
description: Documenting the process of a) patching the Wii Shop Channel binary to communicate with a custom, independent server, and b) creating that server. 
